### ISSUE TITLE
Redis-py version (Windows 10)

### ISSUE THREAD

**Issue by Sonderwoods** [ladybug-tools/honeybee-server-daylight#11]
When uploading the test json objects in localhost:5000 I get the following error.

_VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6_

I ran a pip install redis  and upgraded to 3.3.7, however I'm still getting same error inside my localhost:5000. Any clues?

**Comment by AntoineDao** [comment]
Hi! Thanks for taking an interest. I'm not sure how familiar you are with docker/containerization but essentially you will need to change the redis version to 3.2.0 in [here](https://github.com/ladybug-tools/honeybee-server-daylight/blob/master/honeybee-worker/requirements.txt) and [here](https://github.com/ladybug-tools/honeybee-server-daylight/blob/master/honeybee-server/requirements.txt). Essentially running pip install locally does not affect the docker compose command as docker uses containers (mini virtual machines)  built when you run docker compose.

**Comment by AntoineDao** [comment]
You could also pin the redis container to a previous version [here](https://github.com/ladybug-tools/honeybee-server-daylight/blob/59bdb61d5953d42662cbe1476724f658eefe8632/docker-compose.yml#L49) but I am not sure which version would work...

**Comment by Sonderwoods** [comment]
Thanks, Antoine!
I'll look into it and post a guide here when I find out for future users. I think much of the audience here is architects/engineers and not so much linux/server/docker experts :-)

**Comment by AntoineDao** [comment]
@sonderwoods would you mind making a pull request with the changes you have just made to this repository so others can benefit from your work? :smile:

**Comment by AntoineDao** [comment]
Thanks dude!
