### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/honeybee-server-daylight#5]
I have been playing around on docker and noticed one can trigger automated builds of docker images based on commits to repos. Is this not something that we would want to implement on ladybug and honeybee repos so that when the honeybee server is created it always pulls the latest honeybee docker image based on github repos?

ps: check out my forked automated builds I have set up for testing to get an idea of what it looks like: 
https://hub.docker.com/r/antoinedao/ladybug/
https://hub.docker.com/r/antoinedao/honeybee/builds/

It's a 2 minute job to set up and free (woop) !

**Comment by AntoineDao** [comment]
Just noticed that the "/radiance" folder is part of the gitignore for honeybee git repo. Realise you probably don't want to have the whole of radiance downloaded when cloning honeybee into grasshopper/dynamo... Maybe worth considering some DevOps pipeline like the following:

### Ladybug
1. Commit to ladybug
2. Launch automatic testing on Travis
3. If test passes push commits to "deploy" branch
4. When commits hit "deploy" branch launch build on dockerhub
5. When ladybug docker build succeeds launch honeybee docker build

### Honeybee
1. Commit to honeybee
2. Launch automatic testing on Travis
3. If test passes push commits to "deploy" branch (which includes the radiance binaries)
4. When commits hit "deploy" branch launch build on dockerhub

**Comment by mostaphaRoudsari** [comment]
Hi @AntoineDao, This is a great idea but we need to use tags to ensure it doesn't break the older images.

We need to add a test another level of testing for the flask API to make sure the changes in Ladybug and Honeybee doesn't break the workflow. For instance right now I merged your changes in Honeybee which has changed the id from a number to id and type! If we have this automated system in place the current code on GitHub wouldn't work.

**Comment by AntoineDao** [comment]
Absolutely agreed. This can't be done without testing on both image side and flask side. Once I've got my server
