### ISSUE TITLE
Multi Recipe server

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/honeybee-server-daylight#6]
I have been working on a multi-recipe server for a couple of weeks and it's finally ready for sharing. The key functionalities are:

1. Server Build Up
- [x] Front End  API End Point (Flask)
- [x] Redis db for messaging
- [x] Back End worker to run daylight simulations (horizontally scalable)

2. Honeybee capability
- [x] Daylight Factor simulation
- [x] Radiation simulation
- [x] Annual simulation

There are some limitations which I list below. I accompany each limitation with some proposals on how to fix it.

1. Python containers running in non-official honeybee container:
 * I was testing off a custom honeybee branch so didn't have time to manage potential changes when @mostaphaRoudsari merged the custom branch with the master.
* Someone (probably me) needs to test the workflow a docker image built from freshest honeybee master branch
* worth considering setting some CI/CD test system when committing to honeybee/ladybug to make sure it doesn't break the server.

2. No databasing system to keep results:
* I have been testing using Azure specific tools to keep results which is not interesting for this repo as it's for open source deploy
*  Seems SQLite is the way to go for results logging, would be good for someone to have a look and try to implement a "hb_results.to_sqlite()" method. I can help with sorting out specifics of deploying the database on server using docker.

3. Not PEP8 compliant...
* I was working fast so have made a mostly functional app
* Will need to change functions into proper classes that could then either be merged into honeybee core library or kept here and well documented so that others could participate and help add features to the honeybee server

**Comment by AntoineDao** [comment]
All these changes have been made in the following issue: b0e89a96866430ac8cf58dfd697e9c1f9bb56f16

**Comment by DambronOlivier** [comment]
@AntoineDao ,
Can you confirm this is the way to send the json?
$ curl -X POST -d 'annual.json' http://192.168.99.100:5000/

I get the following:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>

**Comment by mostaphaRoudsari** [comment]
> Someone (probably me) needs to test the workflow a docker image built from freshest honeybee master branch

@AntoineDao, can you send you a pull request from your honeybee branch to the master so we can see the differences. This is something that we need to fix asap before I implement the changes in `AnalysisGrid` and implement the database.

> All these changes have been made in the following issue: b0e89a9

I was meant to push earlier but was playing with a bug all afternoon. Somehow I can't seem to get celery to communicate back cleanly with the flask front end. Fixed it with some super patchy cellotape code for now so that you could see the workflow.

Do you want me to branch out from your branch and try to address the issues that you mentioned?

> - Links are rerouted to hardcoded address of "http://192.168.99.100:5000/" ==> This assumes you are using Docker Toolbox not Docker for Windows.

Oh no! 🤕  Why did you need to do this? This will be an issue for scaling and many more 😈 Let's see if there is a way to avoid this issue.

**Comment by AntoineDao** [comment]
Yeah I was having the same issue with comms back to celery (thus the hardcoded address for now). I'm happy for you to fix on this branch. 

Totally agree that this is garbage for scaling purposes, the idea was mainly to get MVP up and running!

**Comment by mostaphaRoudsari** [comment]
@AntoineDao, sounds good and thank you for pushing the development forward! Can you redirect me to the honeybee branch that you were using for your development or send a pull request as is? I want to review the differences between the two core libraries before getting to the server.

**Comment by AntoineDao** [comment]
Yep, will do so just now. [Here it is.](https://github.com/ladybug-tools/honeybee/pull/212)

**Comment by AntoineDao** [comment]
Stale.
