### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/honeybee-server-daylight#7]
Somewhere on the webserver/github or both there needs to be some sort of API documentation for the proposed end points. Not sure if we should go down the swagger route or if we're happy just writing stuff down manually as we're not expecting too many different end points nor rapid changes.

**Comment by mostaphaRoudsari** [comment]
swagger for the win!

**Comment by mostaphaRoudsari** [comment]
Hmm. My experience with swagger is limited but I think we don't have necessarily to get everything to run from swagger. We can mainly use it as a documentation tool or that's what I was thinking to do.
