### ISSUE TITLE
405 Method no Allowed when posting recipes

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/honeybee-server-daylight#9]
@DambronOlivier posted this in the honeybee repo:

when inside the /dev/run I try :
curl -X POST -d 'annual.json' http://192.168.99.100:5000/

and get:

<title>405 Method Not Allowed</title> Method Not Allowed
The method is not allowed for the requested URL.

How do I move forward?

**Comment by AntoineDao** [comment]
Rereading this now. Yes this is normal! :smile:

Super quick overview of web design for you, there are (2 main types of requests)[https://www.w3schools.com/tags/ref_httpmethods.asp] you can make to a web page:
* GET: you ask for content ==> Show me the home page
* POST: you send content ==> Here's a honeybee recipe, do something with it

**Comment by DambronOlivier** [comment]
I'm trying with the following command
$ curl -X POST /radiation.json http://192.168.99.100:5000/run/radiation

and the web_1 server returns:
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
web_1      |     return self.wsgi_app(environ, start_response)
web_1      |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
web_1      |     response = self.make_response(self.handle_exception(e))
web_1      |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
web_1      |     reraise(exc_type, exc_value, tb)
web_1      |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
web_1      |     response = self.full_dispatch_request()
web_1      |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
web_1      |     rv = self.handle_user_exception(e)
web_1      |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
web_1      |     reraise(exc_type, exc_value, tb)
web_1      |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
web_1      |     rv = self.dispatch_request()
web_1      |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
web_1      |     return self.view_functions[rule.endpoint](**req.view_args)
web_1      |   File "/flask-app/app.py", line 80, in radiation
web_1      |     if "analysis_grids" in content["payload"].keys() \
web_1      | TypeError: 'NoneType' object has no attribute '__getitem__'
web_1      | 192.168.99.1 - - [05/Apr/2018 15:23:35] "POST /run/radiation HTTP/1.1" 500 -

**Comment by AntoineDao** [comment]
Ah! Yes! This is why I need to write the API doc!!

The server is expecting something in the form:
{"payload": HB_JSON_RECIPE}
